#!/usr/bin/env bash
# Script to display username, user id, and home directory from /etc/passwd

while IFS=: read -r username _ userid _ _ home _; do
  echo "$username:$userid:$home"
done < /etc/passwd
