#!/bin/bash
decode() {
	str="$1"
	alphabet="$2"
	base=${#alphabet}
	value=0
	for ((i=0; i<${#str}; i++)); do
		ch="${str:$i:1}"
		digit=$(expr index "$alphabet" "$ch" - 1)
		value=$((value * base + digit))
	done
	echo $value
}

encode() {
	num=$1
	alphabet=$2
	base=${#alphabet}
	result=""
	while (( num > 0 )); do
		rem=$(( num % base ))
		result="${alphabet:$rem:1}$result"
		num=$(( num / base ))
	done
	echo "$result"
}

dec1=$(decode "$WATER" "water")
dec2=$(decode "$STIR" "stir")
sum=$((dec1 + dec2))
encode "$sum" "bestchol"
